name: Shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: echo a string
        run: echo "Hello world"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python Command
        run: | 
          import platform
          print(platform.processor())
          print(platform.java_ver())
        shell: python
